parameters: 
  signSteps: []
  
steps:
- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- script: nbgv cloud
  displayName: Set Version
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.400'

- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.7.0
  inputs:
    versionSpec: 4.7.0
 
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: .\src\Humanizer.sln
    arguments: -c $(BuildConfiguration)   
  displayName: Build  
  
- powershell: |
    mkdir $(Build.ArtifactStagingDirectory)\Packages     
    $version = .\nbgv get-version -f json | ConvertFrom-Json
    ls .\NuSpecs\*.nuspec | %{ nuget pack $_.FullName -version "$($version.NuGetPackageVersion)" -BasePath "src" -NoPackageAnalysis -OutputDirectory $(Build.ArtifactStagingDirectory)\Packages -Properties "RepositoryType=git;RepositoryCommit=$($version.GitCommitId);RepositoryUrl=https://github.com/Humanizr/Humanizer"}
  displayName: Create packages
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
  
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: .\src\Humanizer.Tests\Humanizer.Tests.csproj
    arguments: -c $(BuildConfiguration) --collect:"Code Coverage" -s $(System.DefaultWorkingDirectory)/src/CodeCoverage.runsettings /p:DebugType=portable
  displayName: Run Tests
  
- ${{ parameters.signSteps }}

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Packages
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
  